language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: 8.0
    - php: 8.1
    - php: 8.2

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install

script:
  - composer validate --strict
  - composer test
  - composer cs-ci
